version: "3"
services:
  front:
    image: node:16
    volumes:
      - .:/usr/src
      - front_modules:/usr/src/node_modules #node_modulesはコンテナ内部で用意します
    working_dir: "/usr/src"
    command: sh -c "yarn && yarn build && yarn start"
    tty: true
    ports:
      - "3000:3000"
    environment:
      API_URL_SSR: "http://api:4000"
      NEXT_PUBLIC_API_URL: "http://localhost:4000"
      CHOKIDAR_USEPOLLING: true

volumes:
  front_modules:
